// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eHub.Persistence;

#nullable disable

namespace eHub.Persistence.Migrations
{
    [DbContext(typeof(EHubDbContext))]
    partial class EHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eHub.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AggregateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("BufferDays")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingNumber")
                        .IsUnique();

                    b.HasIndex("AssetId", "Status");

                    b.HasIndex("ExpiresAtUtc", "Status");

                    b.HasIndex("HostId", "CreatedAtUtc");

                    b.HasIndex("RenterId", "CreatedAtUtc");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("eHub.Domain.Bookings.BookingStatusHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("booking_status_history", (string)null);
                });

            modelBuilder.Entity("eHub.Domain.Bookings.BookingTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("booking_timeline_entries", (string)null);
                });

            modelBuilder.Entity("eHub.Persistence.Entities.BookingIdempotencyEntry", b =>
                {
                    b.Property<Guid>("RenterId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("RenterId", "IdempotencyKey");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("booking_idempotency_entries", (string)null);
                });

            modelBuilder.Entity("eHub.Domain.Bookings.Booking", b =>
                {
                    b.OwnsOne("eHub.Domain.Common.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("total_amount");

                            b1.Property<Guid>("CurrencyId")
                                .HasColumnType("uuid")
                                .HasColumnName("total_currency_id");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("eHub.Domain.Common.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_amount");

                            b1.Property<Guid>("CurrencyId")
                                .HasColumnType("uuid")
                                .HasColumnName("unit_currency_id");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("eHub.Domain.Bookings.BookingAssetSnapshot", "AssetSnapshot", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("snapshot_brand");

                            b1.Property<DateTime>("CapturedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("snapshot_captured_at_utc");

                            b1.Property<string>("HostDisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("snapshot_host_display_name");

                            b1.Property<Guid>("HostId")
                                .HasColumnType("uuid")
                                .HasColumnName("snapshot_host_id");

                            b1.Property<string>("Model")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("snapshot_model");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("snapshot_name");

                            b1.Property<string>("PrimaryImageUrls")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("snapshot_primary_image_urls");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("eHub.Domain.Bookings.BookingPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("eHub.Domain.Bookings.BookingTerms", "Terms", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BufferDays")
                                .HasColumnType("integer")
                                .HasColumnName("terms_buffer_days");

                            b1.Property<int?>("MaxRentalDays")
                                .HasColumnType("integer")
                                .HasColumnName("terms_max_rental_days");

                            b1.Property<int?>("MinDriverAge")
                                .HasColumnType("integer")
                                .HasColumnName("terms_min_driver_age");

                            b1.Property<int?>("MinRentalDays")
                                .HasColumnType("integer")
                                .HasColumnName("terms_min_rental_days");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("terms_notes");

                            b1.Property<bool>("RequiresLicense")
                                .HasColumnType("boolean")
                                .HasColumnName("terms_requires_license");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("eHub.Domain.Bookings.DeliveryOption", "Delivery", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("delivery_address_line");

                            b1.Property<bool>("Requested")
                                .HasColumnType("boolean")
                                .HasColumnName("delivery_requested");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.OwnsOne("eHub.Domain.Common.Money", "Fee", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryOptionBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("delivery_fee_amount");

                                    b2.Property<Guid>("CurrencyId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("delivery_fee_currency_id");

                                    b2.HasKey("DeliveryOptionBookingId");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryOptionBookingId");
                                });

                            b1.Navigation("Fee");
                        });

                    b.OwnsOne("eHub.Domain.Bookings.DriverOption", "Driver", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Requested")
                                .HasColumnType("boolean")
                                .HasColumnName("driver_requested");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.OwnsOne("eHub.Domain.Common.Money", "Fee", b2 =>
                                {
                                    b2.Property<Guid>("DriverOptionBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("driver_fee_amount");

                                    b2.Property<Guid>("CurrencyId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("driver_fee_currency_id");

                                    b2.HasKey("DriverOptionBookingId");

                                    b2.ToTable("bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("DriverOptionBookingId");
                                });

                            b1.Navigation("Fee");
                        });

                    b.OwnsOne("eHub.Domain.Bookings.DropoffInformation", "Dropoff", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("dropoff_address_line");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("dropoff_notes");

                            b1.Property<bool>("UseAssetLocation")
                                .HasColumnType("boolean")
                                .HasColumnName("dropoff_use_asset_location");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("eHub.Domain.Bookings.PickupInformation", "Pickup", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("pickup_address_line");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("pickup_notes");

                            b1.Property<bool>("UseAssetLocation")
                                .HasColumnType("boolean")
                                .HasColumnName("pickup_use_asset_location");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("AssetSnapshot")
                        .IsRequired();

                    b.Navigation("Delivery")
                        .IsRequired();

                    b.Navigation("Driver")
                        .IsRequired();

                    b.Navigation("Dropoff")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Pickup")
                        .IsRequired();

                    b.Navigation("Terms")
                        .IsRequired();

                    b.Navigation("TotalPrice")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("eHub.Domain.Bookings.BookingStatusHistoryEntry", b =>
                {
                    b.HasOne("eHub.Domain.Bookings.Booking", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eHub.Domain.Bookings.BookingTimelineEntry", b =>
                {
                    b.HasOne("eHub.Domain.Bookings.Booking", null)
                        .WithMany("Timeline")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eHub.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("StatusHistory");

                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
